name: Docker build

on:
  push:
    branches: [master]
    paths:
      - "src/Dockerfile"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -f "src/Dockerfile"
